name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build mac app
        run: npm run build:mac

      - name: List dist directory (debug)
        run: ls -la dist/

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-dist
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.yml

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build win app
        run: npm run build:win

      - name: List dist directory (debug)
        run: dir dist\

      - name: Upload win artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-dist
          path: |
            dist/*.exe
            dist/*.yml

  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download mac artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac-dist
          path: dist

      - name: Download win artifacts
        uses: actions/download-artifact@v4
        with:
          name: win-dist
          path: dist

      - name: List final dist directory (debug)
        run: ls -la dist/

      - name: Get release notes from CHANGELOG.md
        id: changelog
        run: |
          RELEASE_NOTES=$(awk '/^## /{if (p) exit; p=1; next} p' CHANGELOG.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
